# Name of the workflow
name: Build

# Events used by github actions to know when to execute this workflow
on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      type:
        description: 'Meson buildtype (release, debug, etc.)'
        required: false
        
      test:
        description: 'Run tests (test)'
        required: false

jobs:
  build:
    runs-on: 
      windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2


    - name: Install Meson, Ninja, and Clang with Chocolatey and pip
      shell: pwsh

      run: |
        $ErrorActionPreference = "Stop"
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) 
        {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        }
        
        if (-not (choco list --local-only | Select-String "python")) 
        {
          choco install -y python
        }
        
        if (-not (choco list --local-only | Select-String "ninja")) 
        {
          choco install -y ninja
        }
        
        if (-not (choco list --local-only | Select-String "llvm")) 
        {
          choco install -y llvm
        }
        
        python -m pip install meson


    - name: Run PowerShell build script

      shell: pwsh

      env:
        CC: clang
        CXX: clang++
        BUILD_TYPE: ${{ github.event.inputs.type }}
        RUN_TESTS: ${{ github.event.inputs.test }}

      run: |
        $ErrorActionPreference = "Stop"

        $type = $env:BUILD_TYPE
        $test = $env:RUN_TESTS

        $args = @()
        if (-not [string]::IsNullOrEmpty($type)) { $args += $type }
        if (-not [string]::IsNullOrEmpty($test)) { $args += $test }

        & .\scripts\build.ps1 debug test
